### ISSUE TITLE
Short URLS don't work.

### ISSUE THREAD

**Issue by garnertb** [StatEngine/kibana#6]
To reproduce:

1) Go to a dashboard
2) Click Share
3) In the Share Snapshop section, click Short Url next to the Link option.
4) Copy the generated url and past into a new incognito browser window.

**Comment by chopchop505** [comment]
This was more of a side-effect of authentication.  When you open in the incognito window you aren't authenticated and it craps out.  I cleaned up the logic so you're now redirected to login when trying to access kibana when not authenticated.  Once authenticated in incognito window, you can pass the short url and it works. 

Let me know if still having issues
